# Generated by Django 4.0.4 on 2026-02-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VillageCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_by_user', models.JSONField(blank=True, null=True)),
                ('update_by_user', models.JSONField(blank=True, null=True)),
                ('users_involved', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('cvd_id', models.IntegerField()),
                ('cvd_name', models.CharField(max_length=100)),
                ('village_headquarters_id', models.IntegerField()),
                ('village_headquarters_name', models.CharField(max_length=100)),
                ('canton', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('prefecture', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('members', models.JSONField(default=dict)),
                ('number_of_members', models.IntegerField(default=0)),
                ('members_included_women', models.BooleanField(default=False)),
                ('method_used_to_select_members', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
