# Generated by Django 4.0.4 on 2026-03-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='villagecommittee',
            name='villages_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='villagecommittee',
            name='villages_names',
            field=models.JSONField(default=list),
        ),
    ]
