# Generated by Django 4.0.4 on 2026-03-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_villagecommittee_villages_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='villagecommittee',
            name='cvd_existence',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='villagecommittee',
            name='is_full_staff',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='villagecommittee',
            name='meeting_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
