# Generated by Django 4.0.4 on 2026-09-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_villagecommittee_cvd_existence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='villagecommittee',
            name='delete_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
