# Generated by Django 4.0.4 on 2023-04-13 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process_manager', '0007_task_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('administrative_level', models.IntegerField()),
                ('total_tasks', models.IntegerField(default=0)),
                ('total_tasks_completed', models.IntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_manager.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
