# Generated by Django 4.0.4 on 2023-04-13 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_manager', '0008_aggregatedstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aggregatedstatus',
            old_name='administrative_level',
            new_name='administrative_level_id',
        ),
    ]
