# Generated by Django 4.0.4 on 2023-05-23 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_facilitator_last_activity'),
        ('process_manager', '0009_rename_administrative_level_aggregatedstatus_administrative_level_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeLevelWave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('administrative_level_id', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_manager.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('number', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('number', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacilitatorWave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.facilitator')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_manager.project')),
                ('wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_manager.wave')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacilitatorDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('administrative_level_wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_manager.administrativelevelwave')),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_manager.deployment')),
                ('facilitator_wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_manager.facilitatorwave')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='administrativelevelwave',
            name='wave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_manager.wave'),
        ),
    ]
