# Generated by Django 4.0.4 on 2023-05-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_facilitator_last_activity'),
        ('process_manager', '0010_administrativelevelwave_deployment_wave_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='administrativelevelwave',
            unique_together={('administrative_level_id', 'wave', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='deployment',
            unique_together={('number',)},
        ),
        migrations.AlterUniqueTogether(
            name='facilitatordeployment',
            unique_together={('administrative_level_wave', 'facilitator_wave', 'deployment')},
        ),
        migrations.AlterUniqueTogether(
            name='facilitatorwave',
            unique_together={('facilitator', 'wave', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='wave',
            unique_together={('number',)},
        ),
    ]
