# Generated by Django 4.0.4 on 2023-07-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_manager', '0011_alter_administrativelevelwave_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativelevelwave',
            name='begin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='administrativelevelwave',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilitatordeployment',
            name='begin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilitatordeployment',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilitatorwave',
            name='begin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilitatorwave',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
