# Generated by Django 4.0.4 on 2024-06-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_manager', '0012_administrativelevelwave_begin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedstatus',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
