# Generated by Django 3.2.25 on 2024-09-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_facilitator_last_activity'),
        ('process_manager', '0013_aggregatedstatus_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='facilitators',
            field=models.ManyToManyField(related_name='projects', to='authentication.Facilitator'),
        ),
    ]
