# Generated by Django 4.0.4 on 2024-09-17 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_facilitator_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('process_manager', '0015_project_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='facilitators',
            field=models.ManyToManyField(blank=True, default=[], related_name='projects', to='authentication.facilitator'),
        ),
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(blank=True, default=[], related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
