# Generated by Django 4.0.4 on 2024-09-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_manager', '0016_alter_project_facilitators_alter_project_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='capacity_attachments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='capacity_attachments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='attachments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='capacity_attachments',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
