# Generated by Django 4.0.4 on 2024-09-22 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process_manager', '0017_activity_capacity_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedstatus',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='process_manager.project'),
        ),
    ]
