# Generated by Django 4.0.4 on 2024-11-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_manager', '0019_administrativelevelwave_create_by_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddressesWhichSendEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email_addresses', models.JSONField()),
            ],
        ),
    ]
