# Generated by Django 4.0.4 on 2024-12-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_manager', '0020_emailaddresseswhichsendemails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessAddOrRemoveADL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('move_from', models.CharField(max_length=255)),
                ('move_to', models.CharField(max_length=255)),
                ('administrative_levels', models.JSONField()),
                ('executed', models.BooleanField(default=False)),
            ],
        ),
    ]
