# Generated by Django 4.0.4 on 2024-12-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_manager', '0021_processaddorremoveadl'),
    ]

    operations = [
        migrations.AddField(
            model_name='processaddorremoveadl',
            name='query_action',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processaddorremoveadl',
            name='move_from',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='processaddorremoveadl',
            name='move_to',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='processaddorremoveadl',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
