# Generated by Django 4.0.4 on 2025-01-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_manager', '0022_processaddorremoveadl_query_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaddresseswhichsendemails',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailaddresseswhichsendemails',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='emailaddresseswhichsendemails',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailaddresseswhichsendemails',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='emailaddresseswhichsendemails',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processaddorremoveadl',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processaddorremoveadl',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='processaddorremoveadl',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processaddorremoveadl',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='processaddorremoveadl',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
