# Generated by Django 4.0.4 on 2025-03-29 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process_manager', '0023_emailaddresseswhichsendemails_create_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='process_manager.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aggregatedstatus',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='process_manager.task'),
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_by_user', models.JSONField(blank=True, null=True)),
                ('update_by_user', models.JSONField(blank=True, null=True)),
                ('users_involved', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('couch_id', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField()),
                ('capacity_attachments', models.JSONField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_manager.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='cycles',
            field=models.ManyToManyField(blank=True, default=[], related_name='activities', to='process_manager.cycle'),
        ),
        migrations.AddField(
            model_name='administrativelevelwave',
            name='cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='process_manager.cycle'),
        ),
        migrations.AddField(
            model_name='aggregatedstatus',
            name='cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='process_manager.cycle'),
        ),
        migrations.AddField(
            model_name='facilitatorwave',
            name='cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='process_manager.cycle'),
        ),
        migrations.AddField(
            model_name='phase',
            name='cycles',
            field=models.ManyToManyField(blank=True, default=[], related_name='phases', to='process_manager.cycle'),
        ),
        migrations.AddField(
            model_name='task',
            name='cycles',
            field=models.ManyToManyField(blank=True, default=[], related_name='tasks', to='process_manager.cycle'),
        ),
    ]
