# Generated by Django 4.0.4 on 2025-03-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_manager', '0025_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='cycles',
            field=models.ManyToManyField(default=[], related_name='activities', to='process_manager.cycle'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='cycles',
            field=models.ManyToManyField(default=[], related_name='phases', to='process_manager.cycle'),
        ),
        migrations.AlterField(
            model_name='task',
            name='cycles',
            field=models.ManyToManyField(default=[], related_name='tasks', to='process_manager.cycle'),
        ),
    ]
