# Generated by Django 4.0.4 on 2025-04-02 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_remove_facilitator_type_facilitator_facilitator_type'),
        ('process_manager', '0026_alter_activity_cycles_alter_phase_cycles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedstatus',
            name='facilitator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.facilitator'),
        ),
        migrations.AlterField(
            model_name='aggregatedstatus',
            name='administrative_level_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
