# Generated by Django 4.0.4 on 2025-10-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_manager', '0028_alter_project_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedstatus',
            name='total_tasks_invalidated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggregatedstatus',
            name='total_tasks_invalidated_review',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggregatedstatus',
            name='total_tasks_invalidated_unreview',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggregatedstatus',
            name='total_tasks_validated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggregatedstatus',
            name='total_tasks_waiting_validation',
            field=models.IntegerField(default=0),
        ),
    ]
