# Generated by Django 4.0.4 on 2025-10-17 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_remove_facilitator_cvds_number_and_more'),
        ('process_manager', '0029_aggregatedstatus_total_tasks_invalidated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedStatusFacilitator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_by_user', models.JSONField(blank=True, null=True)),
                ('update_by_user', models.JSONField(blank=True, null=True)),
                ('users_involved', models.JSONField(blank=True, null=True)),
                ('total_tasks_current_project', models.IntegerField(default=0)),
                ('total_tasks_completed_current_project', models.IntegerField(default=0)),
                ('last_activity_current_project', models.DateTimeField(blank=True, null=True)),
                ('total_tasks_stabilized', models.IntegerField(default=0)),
                ('total_tasks_completed_stabilized', models.IntegerField(default=0)),
                ('last_activity_stabilized', models.DateTimeField(blank=True, null=True)),
                ('total_tasks', models.IntegerField(default=0)),
                ('total_tasks_completed', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('total_tasks_validated_current_project', models.IntegerField(default=0)),
                ('total_tasks_invalidated_current_project', models.IntegerField(default=0)),
                ('total_tasks_invalidated_review_current_project', models.IntegerField(default=0)),
                ('total_tasks_invalidated_unreview_current_project', models.IntegerField(default=0)),
                ('total_tasks_waiting_validation_current_project', models.IntegerField(default=0)),
                ('total_tasks_validated_stabilized', models.IntegerField(default=0)),
                ('total_tasks_invalidated_stabilized', models.IntegerField(default=0)),
                ('total_tasks_invalidated_review_stabilized', models.IntegerField(default=0)),
                ('total_tasks_invalidated_unreview_stabilized', models.IntegerField(default=0)),
                ('total_tasks_waiting_validation_stabilized', models.IntegerField(default=0)),
                ('total_tasks_validated', models.IntegerField(default=0)),
                ('total_tasks_invalidated', models.IntegerField(default=0)),
                ('total_tasks_invalidated_review', models.IntegerField(default=0)),
                ('total_tasks_invalidated_unreview', models.IntegerField(default=0)),
                ('total_tasks_waiting_validation', models.IntegerField(default=0)),
                ('cvds_number_current_project', models.IntegerField(default=0)),
                ('villages_number_current_project', models.IntegerField(default=0)),
                ('cvds_number_stabilized', models.IntegerField(default=0)),
                ('villages_number_stabilized', models.IntegerField(default=0)),
                ('cvds_number', models.IntegerField(default=0)),
                ('villages_number', models.IntegerField(default=0)),
                ('new_update_exists', models.BooleanField(default=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_manager.cycle')),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.facilitator')),
                ('last_task_done', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_task_done_facilitators', to='process_manager.task')),
                ('last_task_done_current_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_task_done_current_project_facilitators', to='process_manager.task')),
                ('last_task_done_stabilized', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_task_done_stabilized_facilitators', to='process_manager.task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_manager.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
