# Generated by Django 4.0.4 on 2025-10-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_manager', '0030_aggregatedstatusfacilitator'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedstatusfacilitator',
            name='administrative_level_headquarters_villages_infos',
            field=models.JSONField(default=[]),
        ),
    ]
