# Generated by Django 4.0.4 on 2025-10-22 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process_manager', '0031_aggregatedstatusfacilitator_administrative_level_headquarters_villages_infos'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaddresseswhichsendemails',
            name='project',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='process_manager.project'),
            preserve_default=False,
        ),
    ]
