# Generated by Django 4.0.4 on 2026-02-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_manager', '0032_emailaddresseswhichsendemails_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='name_normalized',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='name_normalized',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='name_normalized',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
