# Generated by Django 4.0.4 on 2026-02-11 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_facilitator_geographical_units'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('process_manager', '0032_emailaddresseswhichsendemails_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_by_user', models.JSONField(blank=True, null=True)),
                ('update_by_user', models.JSONField(blank=True, null=True)),
                ('users_involved', models.JSONField(blank=True, null=True)),
                ('administrative_level_id', models.IntegerField(help_text='ID del nivel administrativo (village/canton)')),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('form_response', models.JSONField(default=list, help_text='Array of objects containing form responses according to JSON Schema')),
                ('validated', models.BooleanField(blank=True, help_text='null=pending, True=valid, False=invalid', null=True)),
                ('updated_after_invalidation', models.BooleanField(default=False, help_text='Indicates whether it was updated after being invalidated')),
                ('validation_comment', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('processed_attachments', models.JSONField(default=list, help_text='[{name, url, type, uploaded_at, size}]')),
                ('synced_to_couch', models.BooleanField(default=False, help_text='TEMPORARY: For tracking during dual-write migration')),
                ('couch_rev', models.CharField(blank=True, help_text='TEMPORARY: Revision of CouchDB for sync', max_length=255)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_manager.cycle')),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_submissions', to='authentication.facilitator')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_manager.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='process_manager.task')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_task_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Submission',
                'verbose_name_plural': 'Task Submissions',
                'db_table': 'process_manager_tasksubmission',
            },
        ),
        migrations.AddField(
            model_name='aggregatedstatus',
            name='total_tasks_invalidated_revised',
            field=models.IntegerField(default=0, help_text='Total invalidated tasks that were updated after'),
        ),
        migrations.AlterField(
            model_name='aggregatedstatusfacilitator',
            name='administrative_level_headquarters_villages_infos',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='TaskUserInvolvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_by_user', models.JSONField(blank=True, null=True)),
                ('update_by_user', models.JSONField(blank=True, null=True)),
                ('users_involved', models.JSONField(blank=True, null=True)),
                ('first_intervention_date', models.DateTimeField()),
                ('last_intervention_date', models.DateTimeField()),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.facilitator')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_involvements', to='process_manager.tasksubmission')),
            ],
            options={
                'verbose_name': 'Task User Involvement',
                'verbose_name_plural': 'Task User Involvements',
                'db_table': 'process_manager_taskuserinvolvement',
            },
        ),
        migrations.CreateModel(
            name='TaskSubmissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_by_user', models.JSONField(blank=True, null=True)),
                ('update_by_user', models.JSONField(blank=True, null=True)),
                ('users_involved', models.JSONField(blank=True, null=True)),
                ('form_response_snapshot', models.JSONField(help_text='Copy of form_response at the time of the change')),
                ('form_fields_snapshot', models.JSONField(help_text='Form schema at the time of editing')),
                ('fields_updated', models.JSONField(default=list, help_text='List of field names that changed')),
                ('attachments_updated', models.JSONField(default=list, help_text='List of attachment names that changed')),
                ('attachments_snapshot', models.JSONField(default=list, help_text='Attachment status at the time of the change')),
                ('page', models.IntegerField(default=0, help_text='Form page number (for multi-page forms)')),
                ('intervention_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('complete', 'Complete'), ('reopen', 'Reopen'), ('validate', 'Validate'), ('invalidate', 'Invalidate')], help_text='Type of intervention performed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facilitator', models.ForeignKey(help_text='Facilitator who made the change', on_delete=django.db.models.deletion.CASCADE, to='authentication.facilitator')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='process_manager.tasksubmission')),
            ],
            options={
                'verbose_name': 'Task Submission History',
                'verbose_name_plural': 'Task Submission Histories',
                'db_table': 'process_manager_tasksubmissionhistory',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeolocationCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_by_user', models.JSONField(blank=True, null=True)),
                ('update_by_user', models.JSONField(blank=True, null=True)),
                ('users_involved', models.JSONField(blank=True, null=True)),
                ('administrative_level_id', models.IntegerField(blank=True, help_text='Administrative level ID if it is an official geolocation', null=True)),
                ('administrative_level_name', models.CharField(blank=True, max_length=255)),
                ('poi_name', models.CharField(blank=True, help_text="Name of the point of interest (for 'others')", max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField(blank=True, help_text='Altitude in meters', null=True)),
                ('accuracy', models.FloatField(blank=True, help_text='Accuracy in meters', null=True)),
                ('coords_created', models.DateTimeField(help_text='Moment the coordinates were captured')),
                ('coords_updated', models.DateTimeField(auto_now=True)),
                ('synced', models.BooleanField(default=False)),
                ('device_info', models.JSONField(blank=True, default=dict, help_text='{device_model, os_version, app_version}')),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geolocation_captures', to='authentication.facilitator')),
            ],
            options={
                'verbose_name': 'Geolocation Capture',
                'verbose_name_plural': 'Geolocation Captures',
                'db_table': 'process_manager_geolocationcapture',
            },
        ),
        migrations.CreateModel(
            name='AttachmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_by_user', models.JSONField(blank=True, null=True)),
                ('update_by_user', models.JSONField(blank=True, null=True)),
                ('users_involved', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(help_text='File or URL if using S3', upload_to='task_attachments/%Y/%m/%d/')),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.IntegerField(help_text='Size in bytes')),
                ('order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('s3_bucket', models.CharField(blank=True, max_length=255)),
                ('s3_key', models.CharField(blank=True, max_length=500)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='process_manager.tasksubmission')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_attachments', to='process_manager.task')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.facilitator')),
            ],
            options={
                'verbose_name': 'Attachment File',
                'verbose_name_plural': 'Attachment Files',
                'db_table': 'process_manager_attachmentfile',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='taskuserinvolvement',
            index=models.Index(fields=['submission', 'facilitator'], name='process_man_submiss_c03810_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskuserinvolvement',
            unique_together={('submission', 'facilitator')},
        ),
        migrations.AddIndex(
            model_name='tasksubmissionhistory',
            index=models.Index(fields=['submission', '-created_at'], name='process_man_submiss_046235_idx'),
        ),
        migrations.AddIndex(
            model_name='tasksubmissionhistory',
            index=models.Index(fields=['facilitator', '-created_at'], name='process_man_facilit_8f6589_idx'),
        ),
        migrations.AddIndex(
            model_name='tasksubmission',
            index=models.Index(fields=['task', 'administrative_level_id'], name='process_man_task_id_0bbe93_idx'),
        ),
        migrations.AddIndex(
            model_name='tasksubmission',
            index=models.Index(fields=['facilitator', 'completed'], name='process_man_facilit_4846cc_idx'),
        ),
        migrations.AddIndex(
            model_name='tasksubmission',
            index=models.Index(fields=['project', 'cycle', 'completed'], name='process_man_project_ce409c_idx'),
        ),
        migrations.AddIndex(
            model_name='tasksubmission',
            index=models.Index(fields=['validated', 'completed'], name='process_man_validat_9619e6_idx'),
        ),
        migrations.AddIndex(
            model_name='tasksubmission',
            index=models.Index(fields=['administrative_level_id', 'project', 'cycle'], name='process_man_adminis_de7e9c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tasksubmission',
            unique_together={('task', 'facilitator', 'administrative_level_id', 'project', 'cycle')},
        ),
        migrations.AddIndex(
            model_name='geolocationcapture',
            index=models.Index(fields=['facilitator', 'administrative_level_id'], name='process_man_facilit_4d720e_idx'),
        ),
        migrations.AddIndex(
            model_name='geolocationcapture',
            index=models.Index(fields=['facilitator', 'coords_created'], name='process_man_facilit_d737fa_idx'),
        ),
        migrations.AddIndex(
            model_name='geolocationcapture',
            index=models.Index(fields=['latitude', 'longitude'], name='process_man_latitud_87a793_idx'),
        ),
        migrations.AddIndex(
            model_name='geolocationcapture',
            index=models.Index(fields=['administrative_level_id'], name='process_man_adminis_ec4a2b_idx'),
        ),
        migrations.AddIndex(
            model_name='attachmentfile',
            index=models.Index(fields=['task', 'submission'], name='process_man_task_id_7e253c_idx'),
        ),
        migrations.AddIndex(
            model_name='attachmentfile',
            index=models.Index(fields=['uploaded_by', '-uploaded_at'], name='process_man_uploade_0a9884_idx'),
        ),
    ]
