# Generated by Django 4.0.4 on 2026-02-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_manager', '0033_activity_name_normalized_phase_name_normalized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregatedstatusfacilitator',
            name='administrative_level_headquarters_villages_infos',
            field=models.JSONField(default=list),
        ),
    ]
