# Generated by Django 4.0.4 on 2026-02-13 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_facilitator_geographical_units'),
        ('process_manager', '0033_tasksubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmissionhistory',
            name='missing_facilitator',
            field=models.JSONField(blank=True, default=dict, help_text='TEMPORARY: For tracking missing facilitators during migration'),
        ),
        migrations.AddField(
            model_name='taskuserinvolvement',
            name='missing_facilitator',
            field=models.JSONField(blank=True, default=dict, help_text='TEMPORARY: For tracking missing facilitators during migration'),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='facilitator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_submissions', to='authentication.facilitator'),
        ),
        migrations.AlterField(
            model_name='tasksubmissionhistory',
            name='facilitator',
            field=models.ForeignKey(help_text='Facilitator who made the change', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.facilitator'),
        ),
        migrations.AlterField(
            model_name='taskuserinvolvement',
            name='facilitator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.facilitator'),
        ),
    ]
