# Generated by Django 4.0.4 on 2026-02-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_manager', '0034_tasksubmissionhistory_missing_facilitator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='support_attachments',
            field=models.BooleanField(default=False),
        ),
    ]
