# Generated by Django 4.0.4 on 2026-02-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_manager', '0034_alter_aggregatedstatusfacilitator_administrative_level_headquarters_villages_infos'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cycle',
            unique_together={('project', 'order')},
        ),
    ]
