# Generated by Django 4.0.4 on 2026-07-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_manager', '0035_alter_cycle_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedstatus',
            name='total_tasks_invalidated_review_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggregatedstatus',
            name='total_tasks_invalidated_review_in_pending',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggregatedstatus',
            name='total_tasks_invalidated_unreview_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggregatedstatus',
            name='total_tasks_invalidated_unreview_in_pending',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggregatedstatusfacilitator',
            name='total_tasks_invalidated_review_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggregatedstatusfacilitator',
            name='total_tasks_invalidated_review_completed_stabilized',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggregatedstatusfacilitator',
            name='total_tasks_invalidated_review_in_pending',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggregatedstatusfacilitator',
            name='total_tasks_invalidated_review_in_pending_stabilized',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggregatedstatusfacilitator',
            name='total_tasks_invalidated_unreview_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggregatedstatusfacilitator',
            name='total_tasks_invalidated_unreview_completed_stabilized',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggregatedstatusfacilitator',
            name='total_tasks_invalidated_unreview_in_pending',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggregatedstatusfacilitator',
            name='total_tasks_invalidated_unreview_in_pending_stabilized',
            field=models.IntegerField(default=0),
        ),
    ]
