# Generated by Django 4.0.4 on 2026-07-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_manager', '0036_aggregatedstatus_total_tasks_invalidated_review_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedstatusfacilitator',
            name='total_tasks_invalidated_review_completed_current_project',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggregatedstatusfacilitator',
            name='total_tasks_invalidated_review_in_pending_current_project',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggregatedstatusfacilitator',
            name='total_tasks_invalidated_unreview_completed_current_project',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggregatedstatusfacilitator',
            name='total_tasks_invalidated_unreview_in_pending_current_project',
            field=models.IntegerField(default=0),
        ),
    ]
