# Generated by Django 4.0.4 on 2026-07-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_manager', '0037_aggregatedstatusfacilitator_total_tasks_invalidated_review_completed_current_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedstatus',
            name='its_adl_has_sub_project',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aggregatedstatus',
            name='task_needs_subproject',
            field=models.BooleanField(default=False),
        ),
    ]
