# Generated by Django 4.0.4 on 2026-09-11 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_basemodel_delete_by_user'),
        ('process_manager', '0040_project_concept_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='share_mode',
            field=models.CharField(choices=[('none', 'Aucun partage'), ('fixed_canton', 'Automatique — villages sièges du canton'), ('facilitator_then_validator', 'Facilitateur puis validateur'), ('validator_only', 'Validateur uniquement')], default='none', max_length=32),
        ),
        migrations.CreateModel(
            name='TaskShareRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_by_user', models.JSONField(blank=True, null=True)),
                ('update_by_user', models.JSONField(blank=True, null=True)),
                ('delete_by_user', models.JSONField(blank=True, null=True)),
                ('users_involved', models.JSONField(blank=True, null=True)),
                ('administrative_level_id', models.IntegerField()),
                ('couch_task_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('in_progress', 'En cours'), ('completed', 'Achevée'), ('validated', 'Validée'), ('invalidated', 'Invalidée')], default='in_progress', max_length=20)),
                ('share_values', models.JSONField(blank=True, null=True)),
                ('share_targets', models.JSONField(blank=True, default=list)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='process_manager.cycle')),
                ('facilitator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.facilitator')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='process_manager.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_records', to='process_manager.task')),
            ],
            options={
                'unique_together': {('task', 'project', 'cycle', 'administrative_level_id')},
            },
        ),
    ]
