# Generated by Django 4.0.4 on 2026-09-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('process_manager', '0041_task_share_mode_tasksharerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='groups_collectors',
            field=models.ManyToManyField(blank=True, related_name='tasks_collectible', to='auth.group'),
        ),
        migrations.AddField(
            model_name='task',
            name='non_blocking',
            field=models.BooleanField(default=False),
        ),
    ]
