# Generated by Django 4.0.4 on 2026-09-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_manager', '0042_task_groups_collectors_task_non_blocking'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='visibility_condition',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
