# Generated by Django 4.2.30 on 2026-09-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_manager', '0043_task_visibility_condition'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aggregatedstatus',
            index=models.Index(fields=['project', 'cycle', 'administrative_level_id'], name='aggstatus_proj_cycle_adl_idx'),
        ),
        migrations.AddIndex(
            model_name='aggregatedstatus',
            index=models.Index(fields=['project', 'cycle', '-updated_date'], name='aggstatus_proj_cycle_upd_idx'),
        ),
    ]
