# Generated by Django 4.0.4 on 2024-08-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_facilitator_news_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='administrative_level_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Administrative level'),
        ),
        migrations.AlterField(
            model_name='news',
            name='project_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Project'),
        ),
    ]
