# Generated by Django 4.0.4 on 2024-08-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='project_id',
        ),
        migrations.AddField(
            model_name='news',
            name='project_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Project'),
        ),
    ]
