# Generated by Django 4.0.4 on 2024-08-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_news_project_id_news_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='project_name',
        ),
        migrations.AddField(
            model_name='news',
            name='projects_name',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
