# Generated by Django 4.0.4 on 2024-08-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_news_project_name_news_projects_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='administrative_level_id',
        ),
        migrations.AddField(
            model_name='news',
            name='administrative_levels_id',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
