# Generated by Django 4.0.4 on 2024-08-21 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_news_administrative_level_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='administrative_levels_id',
            new_name='administrative_levels',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='projects_name',
            new_name='projects',
        ),
    ]
