# Generated by Django 4.0.4 on 2024-08-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_rename_administrative_levels_id_news_administrative_levels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfile',
            name='user_email',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsfile',
            name='username',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
