# Generated by Django 4.0.4 on 2024-08-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_newsfile_user_email_newsfile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfile',
            name='user_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
