# Generated by Django 4.0.4 on 2024-08-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_newsfile_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='news',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='news',
            name='total_men_between_10_35_died',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total men between 10 and 35 died'),
        ),
        migrations.AddField(
            model_name='news',
            name='total_men_between_10_35_injured',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total men between 10 and 35 injured'),
        ),
        migrations.AddField(
            model_name='news',
            name='total_men_over_35_died',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total men over 35 died'),
        ),
        migrations.AddField(
            model_name='news',
            name='total_men_over_35_injured',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total men over 35 injured'),
        ),
        migrations.AddField(
            model_name='news',
            name='total_men_present_over_35',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total men present over 35'),
        ),
        migrations.AddField(
            model_name='news',
            name='total_men_present_under_35',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total men present under 35'),
        ),
        migrations.AddField(
            model_name='news',
            name='total_men_under_10_died',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total men under 10 died'),
        ),
        migrations.AddField(
            model_name='news',
            name='total_men_under_10_injured',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total men under 10 injured'),
        ),
        migrations.AddField(
            model_name='news',
            name='total_people_between_10_35_died',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total people between 10 and 35 died'),
        ),
        migrations.AddField(
            model_name='news',
            name='total_people_between_10_35_injured',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total people between 10 and 35 injured'),
        ),
        migrations.AddField(
            model_name='news',
            name='total_people_died',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total people died'),
        ),
        migrations.AddField(
            model_name='news',
            name='total_people_injured',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total people injured'),
        ),
        migrations.AddField(
            model_name='news',
            name='total_people_over_35_died',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total people over 35 died'),
        ),
        migrations.AddField(
            model_name='news',
            name='total_people_over_35_injured',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total people over 35 injured'),
        ),
        migrations.AddField(
            model_name='news',
            name='total_people_present',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total people present'),
        ),
        migrations.AddField(
            model_name='news',
            name='total_people_present_over_35',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total people present over 35'),
        ),
        migrations.AddField(
            model_name='news',
            name='total_people_present_under_35',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total people present under 35'),
        ),
        migrations.AddField(
            model_name='news',
            name='total_people_under_10_died',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total people under 10 died'),
        ),
        migrations.AddField(
            model_name='news',
            name='total_people_under_10_injured',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total people under 10 injured'),
        ),
        migrations.AddField(
            model_name='news',
            name='total_women_between_10_35_died',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total women between 10 and 35 died'),
        ),
        migrations.AddField(
            model_name='news',
            name='total_women_between_10_35_injured',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total women between 10 and 35 injured'),
        ),
        migrations.AddField(
            model_name='news',
            name='total_women_over_35_died',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total women over 35 died'),
        ),
        migrations.AddField(
            model_name='news',
            name='total_women_over_35_injured',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total women over 35 injured'),
        ),
        migrations.AddField(
            model_name='news',
            name='total_women_present_over_35',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total women present over 35'),
        ),
        migrations.AddField(
            model_name='news',
            name='total_women_present_under_35',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total women present under 35'),
        ),
        migrations.AddField(
            model_name='news',
            name='total_women_under_10_died',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total women under 10 died'),
        ),
        migrations.AddField(
            model_name='news',
            name='total_women_under_10_injured',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total women under 10 injured'),
        ),
    ]
