# Generated by Django 4.0.4 on 2024-08-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_news_latitude_news_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='total_people_by_the_event',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total people affected by the event'),
        ),
    ]
