# Generated by Django 4.0.4 on 2024-08-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='Event date'),
        ),
        migrations.AddField(
            model_name='news',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publication date'),
        ),
    ]
