# Generated by Django 4.0.4 on 2026-09-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_category_create_by_user_category_update_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='delete_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='delete_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsfile',
            name='delete_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='delete_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='delete_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
