# Generated by Django 4.0.4 on 2024-09-24 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('process_manager', '0019_administrativelevelwave_create_by_user_and_more'),
        ('authentication', '0010_alter_facilitator_develop_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_by_user', models.JSONField(blank=True, null=True)),
                ('update_by_user', models.JSONField(blank=True, null=True)),
                ('users_involved', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(max_length=50, verbose_name='Type')),
                ('name', models.CharField(max_length=255, verbose_name='Activity')),
                ('description', models.TextField(verbose_name='Description')),
                ('administrative_level_id', models.IntegerField(blank=True, null=True, verbose_name='Locality ID')),
                ('administrative_level_name', models.IntegerField(blank=True, null=True, verbose_name='Locality Name')),
                ('planned_date', models.DateField(verbose_name='Plan date')),
                ('planned_datetime_start', models.DateTimeField(blank=True, null=True, verbose_name='Start')),
                ('planned_datetime_end', models.DateTimeField(blank=True, null=True, verbose_name='End')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('undo', models.BooleanField(default=False, verbose_name='Undo')),
                ('is_another', models.BooleanField(default=False, verbose_name='Another activity')),
                ('is_free_task', models.BooleanField(default=False, verbose_name='Another activity done is free task?')),
                ('free_task_title', models.CharField(max_length=255, verbose_name='The title of the free activity done')),
                ('another_detail', models.JSONField(blank=True, null=True)),
                ('comment', models.TextField(verbose_name='Report')),
                ('validated', models.BooleanField(default=None, verbose_name='Validated')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_activities', to='process_manager.activity')),
                ('facilitator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_activities', to='authentication.facilitator')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_activities', to='process_manager.phase')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityValidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_by_user', models.JSONField(blank=True, null=True)),
                ('update_by_user', models.JSONField(blank=True, null=True)),
                ('users_involved', models.JSONField(blank=True, null=True)),
                ('validated', models.BooleanField(default=None, verbose_name='Validated')),
                ('comment', models.TextField(verbose_name='Report')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.activity')),
                ('facilitator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_activities_validates', to='authentication.facilitator')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_activities_validates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_by_user', models.JSONField(blank=True, null=True)),
                ('update_by_user', models.JSONField(blank=True, null=True)),
                ('users_involved', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('principal', models.BooleanField(default=False)),
                ('date_taken', models.DateField()),
                ('file_type', models.CharField(default='image', max_length=100)),
                ('username', models.CharField(max_length=255)),
                ('user_email', models.CharField(blank=True, max_length=255, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.activity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
