# Generated by Django 4.0.4 on 2024-09-24 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process_manager', '0019_administrativelevelwave_create_by_user_and_more'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='planning_activities', to='process_manager.project'),
            preserve_default=False,
        ),
    ]
