# Generated by Django 4.0.4 on 2024-09-24 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0010_alter_facilitator_develop_mode'),
        ('planning', '0002_activity_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_by_user', models.JSONField(blank=True, null=True)),
                ('update_by_user', models.JSONField(blank=True, null=True)),
                ('users_involved', models.JSONField(blank=True, null=True)),
                ('comment', models.TextField(verbose_name='Comment')),
                ('type', models.CharField(default='comment', max_length=25)),
                ('comment_read', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.activity')),
                ('facilitator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_activity_comments', to='authentication.facilitator')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_activity_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
