# Generated by Django 4.0.4 on 2024-09-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_activitycomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Report'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='free_task_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='The title of the free activity done'),
        ),
    ]
