# Generated by Django 4.0.4 on 2024-09-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_alter_activity_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='administrative_level_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Locality Name'),
        ),
    ]
