# Generated by Django 4.0.4 on 2024-09-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_alter_activity_administrative_level_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='validated',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Validated'),
        ),
    ]
