# Generated by Django 4.0.4 on 2024-09-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_alter_activity_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='completed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='is_another',
            field=models.BooleanField(blank=True, null=True, verbose_name='Another activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='is_free_task',
            field=models.BooleanField(blank=True, null=True, verbose_name='Another activity done is free task?'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='undo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Undo'),
        ),
    ]
