# Generated by Django 4.0.4 on 2024-09-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_alter_activity_completed_alter_activity_is_another_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='undo_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Report (Undo)'),
        ),
    ]
