# Generated by Django 4.0.4 on 2024-09-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_activity_undo_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='administrative_level_id',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='administrative_level_name',
        ),
        migrations.AddField(
            model_name='activity',
            name='administrative_level_ids',
            field=models.JSONField(blank=True, null=True, verbose_name='Locality ID'),
        ),
        migrations.AddField(
            model_name='activity',
            name='administrative_levels',
            field=models.JSONField(blank=True, null=True, verbose_name='Localities'),
        ),
    ]
