# Generated by Django 4.0.4 on 2024-10-01 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('process_manager', '0019_administrativelevelwave_create_by_user_and_more'),
        ('planning', '0009_remove_activity_administrative_level_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationGroupsProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_by_user', models.JSONField(blank=True, null=True)),
                ('update_by_user', models.JSONField(blank=True, null=True)),
                ('users_involved', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('planners_groups', models.ManyToManyField(default=[], related_name='planners_groups', to='auth.group')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_group', to='process_manager.project')),
                ('validators_groups', models.ManyToManyField(default=[], related_name='validators_groups', to='auth.group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
