# Generated by Django 4.0.4 on 2024-10-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0010_validationgroupsprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityvalidate',
            name='comment_read',
            field=models.BooleanField(default=False),
        ),
    ]
