# Generated by Django 4.0.4 on 2024-10-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_activityvalidate_comment_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityvalidate',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Report'),
        ),
    ]
