# Generated by Django 4.0.4 on 2024-10-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0012_alter_activityvalidate_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='edit_after_invalidation',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
