# Generated by Django 4.0.4 on 2024-10-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0013_activity_edit_after_invalidation'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='vacation_return_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Return date'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='planned_date',
            field=models.DateField(blank=True, null=True, verbose_name='Plan date'),
        ),
    ]
