# Generated by Django 4.0.4 on 2024-10-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0014_activity_vacation_return_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='vacation_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vacation type'),
        ),
    ]
