# Generated by Django 4.0.4 on 2024-10-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0015_activity_vacation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='component',
            field=models.TextField(blank=True, null=True, verbose_name='Component'),
        ),
    ]
