# Generated by Django 4.0.4 on 2024-10-30 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0017_activitydeadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitydeadline',
            old_name='planners_groups',
            new_name='activities_deadline_groups',
        ),
    ]
