# Generated by Django 4.0.4 on 2024-11-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0018_rename_planners_groups_activitydeadline_activities_deadline_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_period_dates',
            field=models.BooleanField(blank=True, null=True, verbose_name='Date range?'),
        ),
    ]
