# Generated by Django 4.0.4 on 2025-01-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0019_activity_is_period_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='geolocation_end',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='geolocation_start',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
