# Generated by Django 4.0.4 on 2025-01-07 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0020_activity_geolocation_end_activity_geolocation_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='geolocation_end',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='geolocation_start',
        ),
        migrations.CreateModel(
            name='ActivityGeolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_by_user', models.JSONField(blank=True, null=True)),
                ('update_by_user', models.JSONField(blank=True, null=True)),
                ('users_involved', models.JSONField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('geolocation_start', models.JSONField(blank=True, null=True)),
                ('geolocation_end', models.JSONField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.activity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
