# Generated by Django 4.0.4 on 2025-01-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0021_remove_activity_geolocation_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitygeolocation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='activitygeolocation',
            name='longitude',
        ),
        migrations.AddField(
            model_name='activitygeolocation',
            name='latitude_end',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitygeolocation',
            name='latitude_start',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='activitygeolocation',
            name='longituden_end',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitygeolocation',
            name='longituden_start',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='activitygeolocation',
            name='taking_datetime_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitygeolocation',
            name='taking_datetime_start',
            field=models.DateTimeField(null=True),
        ),
    ]
