# Generated by Django 4.0.4 on 2025-01-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0022_remove_activitygeolocation_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitygeolocation',
            name='taking_date',
            field=models.DateField(null=True),
        ),
    ]
