# Generated by Django 4.0.4 on 2025-01-07 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0023_activitygeolocation_taking_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitygeolocation',
            old_name='longituden_end',
            new_name='longitude_end',
        ),
        migrations.RenameField(
            model_name='activitygeolocation',
            old_name='longituden_start',
            new_name='longitude_start',
        ),
    ]
