# Generated by Django 4.0.4 on 2025-01-07 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0024_rename_longituden_end_activitygeolocation_longitude_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitygeolocation',
            old_name='taking_date',
            new_name='planning_date',
        ),
    ]
