# Generated by Django 4.0.4 on 2025-10-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0025_rename_taking_date_activitygeolocation_planning_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='total_men_present_over_35',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total men present over 35'),
        ),
        migrations.AddField(
            model_name='activity',
            name='total_men_present_under_35',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total men present under 35'),
        ),
        migrations.AddField(
            model_name='activity',
            name='total_people_present',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total people present'),
        ),
        migrations.AddField(
            model_name='activity',
            name='total_people_present_over_35',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total people present over 35'),
        ),
        migrations.AddField(
            model_name='activity',
            name='total_people_present_under_35',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total people present under 35'),
        ),
        migrations.AddField(
            model_name='activity',
            name='total_women_present_over_35',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total women present over 35'),
        ),
        migrations.AddField(
            model_name='activity',
            name='total_women_present_under_35',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total women present under 35'),
        ),
    ]
