# Generated by Django 4.0.4 on 2026-05-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0026_activity_total_men_present_over_35_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='work_environment',
            field=models.CharField(choices=[('Office', 'Office'), ('Field', 'Field'), ('Hotel/Workshop', 'Hotel/Workshop'), ('Remote', 'Remote'), ('Overseas assignment', 'Overseas assignment'), ('Other', 'Other')], default=None, max_length=100, null=True, verbose_name='Work Environment'),
        ),
    ]
