# Generated by Django 4.0.4 on 2026-09-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0027_activity_work_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='delete_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitycomment',
            name='delete_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitydeadline',
            name='delete_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityfile',
            name='delete_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitygeolocation',
            name='delete_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityvalidate',
            name='delete_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validationgroupsprocess',
            name='delete_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
