# Generated by Django 4.0.4 on 2024-02-15 09:35

from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto3
import supportmaterial.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Lesson Name')),
                ('rank', models.IntegerField(verbose_name='Rank')),
                ('image', models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=supportmaterial.models.app_path, verbose_name='Illustration Image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Lesson Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Subject Name')),
                ('rank', models.IntegerField(verbose_name='Rank')),
                ('image', models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=supportmaterial.models.app_path, verbose_name='Illustration Image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Subject Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name of resource')),
                ('rank', models.IntegerField(verbose_name='Rank')),
                ('file', models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=supportmaterial.models.app_path, verbose_name='File')),
                ('file_aws_s3_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='File AWS S3 Url')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Supporting Material Description')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supportmaterial.lesson', verbose_name='Lesson')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supportmaterial.subject', verbose_name='Subject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supportmaterial.subject', verbose_name='Subject'),
        ),
    ]
