# Generated by Django 4.0.4 on 2024-02-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportmaterial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Subject Name'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='rank',
            field=models.IntegerField(unique=True, verbose_name='Rank'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('subject', 'rank'), ('subject', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='supportingmaterial',
            unique_together={('subject', 'rank'), ('subject', 'name'), ('lesson', 'rank'), ('lesson', 'name')},
        ),
    ]
