# Generated by Django 4.0.4 on 2024-02-15 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supportmaterial', '0002_alter_subject_name_alter_subject_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supportmaterial.subject'),
        ),
    ]
