# Generated by Django 4.0.4 on 2024-02-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportmaterial', '0003_subject_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Subject Name'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='rank',
            field=models.IntegerField(verbose_name='Rank'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('rank',), ('parent', 'rank'), ('parent', 'name'), ('name',)},
        ),
    ]
