# Generated by Django 4.0.4 on 2024-02-15 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supportmaterial', '0004_alter_subject_name_alter_subject_rank_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('parent', 'rank'), ('parent', 'name')},
        ),
    ]
