# Generated by Django 4.0.4 on 2024-09-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportmaterial', '0005_alter_subject_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportingmaterial',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportingmaterial',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportingmaterial',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
