# Generated by Django 4.0.4 on 2026-01-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supportmaterial', '0006_lesson_create_by_user_lesson_update_by_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supportingmaterial',
            unique_together={('lesson', 'name'), ('lesson', 'rank')},
        ),
    ]
