# Generated by Django 4.0.4 on 2024-01-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_storeapp_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproject',
            name='package',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Project Package'),
        ),
    ]
