# Generated by Django 4.0.4 on 2024-01-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_alter_storeproject_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeapp',
            name='app_code',
            field=models.CharField(max_length=255, unique=True, verbose_name='App Code'),
        ),
    ]
