# Generated by Django 4.0.4 on 2024-01-31 11:42

from django.db import migrations, models
import storeapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0004_alter_storeapp_app_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeapp',
            name='apk',
            field=models.FileField(upload_to=storeapp.models.app_path, verbose_name='APK'),
        ),
    ]
