# Generated by Django 4.0.4 on 2024-01-31 12:10

from django.db import migrations, models
import storages.backends.s3boto3
import storeapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0005_alter_storeapp_apk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeapp',
            name='apk',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=storeapp.models.app_path, verbose_name='APK'),
        ),
    ]
