# Generated by Django 4.0.4 on 2024-01-31 12:33

from django.db import migrations, models
import storages.backends.s3boto3
import storeapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0006_alter_storeapp_apk'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeapp',
            name='apk_aws_s3_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='APK AWS S3 Url'),
        ),
        migrations.AlterField(
            model_name='storeapp',
            name='apk',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=storeapp.models.app_path, verbose_name='APK'),
        ),
    ]
