# Generated by Django 4.0.4 on 2024-01-31 14:40

from django.db import migrations, models
import storages.backends.s3boto3
import storeapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0007_storeapp_apk_aws_s3_url_alter_storeapp_apk'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproject',
            name='image',
            field=models.ImageField(default=None, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=storeapp.models.app_path, verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storeproject',
            name='package',
            field=models.CharField(default=None, max_length=100, unique=True, verbose_name='Project Package'),
            preserve_default=False,
        ),
    ]
