# Generated by Django 4.0.4 on 2024-01-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0008_storeproject_image_alter_storeproject_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeapp',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='storeapp',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='storeproject',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='storeproject',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
