# Generated by Django 4.0.4 on 2024-08-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0009_storeapp_created_date_storeapp_updated_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproject',
            name='playstore_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PlayStore Url'),
        ),
    ]
