# Generated by Django 4.0.4 on 2024-09-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0010_storeproject_playstore_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeapp',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeapp',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeapp',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeproject',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeproject',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeproject',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
