# Generated by Django 4.0.4 on 2026-08-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0011_storeapp_create_by_user_storeapp_update_by_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeapp',
            name='app_code',
            field=models.CharField(max_length=255, verbose_name='App Code'),
        ),
        migrations.AlterField(
            model_name='storeapp',
            name='version_code',
            field=models.IntegerField(verbose_name='Version Code'),
        ),
        migrations.AlterUniqueTogether(
            name='storeapp',
            unique_together={('project', 'version_code'), ('project', 'app_code')},
        ),
    ]
