# Generated by Django 4.0.4 on 2026-02-11 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_facilitator_geographical_units'),
        ('storeapp', '0011_storeapp_create_by_user_storeapp_update_by_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_by_user', models.JSONField(blank=True, null=True)),
                ('update_by_user', models.JSONField(blank=True, null=True)),
                ('users_involved', models.JSONField(blank=True, null=True)),
                ('sync_timestamp', models.DateTimeField(auto_now_add=True)),
                ('sync_type', models.CharField(choices=[('delta', 'Delta Sync'), ('batch', 'Batch Upload'), ('full', 'Full Sync')], max_length=50)),
                ('entities_synced', models.JSONField(default=dict, help_text='{"task_submissions": 10, "geolocations": 5}')),
                ('conflicts_count', models.IntegerField(default=0)),
                ('conflicts_data', models.JSONField(default=list, help_text='Details of conflicts encountered')),
                ('errors_count', models.IntegerField(default=0)),
                ('errors_data', models.JSONField(default=list, help_text='Details of errors that occurred')),
                ('duration_ms', models.IntegerField(help_text='Synchronization duration in milliseconds')),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='authentication.facilitator')),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'db_table': 'process_manager_synclog',
                'ordering': ['-sync_timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['facilitator', '-sync_timestamp'], name='process_man_facilit_825615_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['-sync_timestamp'], name='process_man_sync_ti_cdc5e1_idx'),
        ),
    ]
