# Generated by Django 4.0.4 on 2026-09-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0012_alter_storeapp_app_code_alter_storeapp_version_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeapp',
            name='delete_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeproject',
            name='delete_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
