# Generated by Django 4.0.4 on 2026-09-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationcode',
            name='delete_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
