# Generated by Django 4.0.4 on 2023-04-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_facilitator_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitator',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='sex',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='sex'),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='total_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='total_tasks_completed',
            field=models.IntegerField(default=0),
        ),
    ]
