# Generated by Django 4.0.4 on 2023-04-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_facilitator_email_facilitator_name_facilitator_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitator',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
