# Generated by Django 4.0.4 on 2024-09-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_facilitator_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitator',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='code'),
        ),
    ]
