# Generated by Django 4.0.4 on 2024-09-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_facilitator_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitator',
            name='no_sql_dbs_names',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
