# Generated by Django 4.0.4 on 2024-09-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_facilitator_no_sql_dbs_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitator',
            name='develop_mode',
            field=models.BooleanField(default=False, verbose_name='develop mode'),
        ),
    ]
