# Generated by Django 4.0.4 on 2025-02-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_facilitator_develop_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitator',
            name='type',
            field=models.CharField(choices=[('COMMUNITY_FACILITATOR', 'Community facilitator'), ('TECHNICAL_FACILITATOR', 'Technical facilitator')], default='COMMUNITY_FACILITATOR', max_length=100),
        ),
    ]
