# Generated by Django 4.0.4 on 2025-02-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_facilitator_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitator',
            name='type',
        ),
        migrations.AddField(
            model_name='facilitator',
            name='facilitator_type',
            field=models.CharField(choices=[('community_facilitator', 'Community facilitator'), ('technical_facilitator', 'Technical facilitator')], default='community_facilitator', max_length=100),
        ),
    ]
