# Generated by Django 4.0.4 on 2025-04-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_remove_facilitator_type_facilitator_facilitator_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitator',
            name='administrative_levels',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='administrative_levels_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
