# Generated by Django 4.0.4 on 2025-04-03 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_facilitator_administrative_levels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitator',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='facilitator',
            name='total_tasks',
        ),
        migrations.RemoveField(
            model_name='facilitator',
            name='total_tasks_completed',
        ),
    ]
