# Generated by Django 4.0.4 on 2025-04-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_remove_facilitator_last_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitator',
            name='create_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='update_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='users_involved',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
