# Generated by Django 4.0.4 on 2026-02-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_remove_facilitator_cvds_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitator',
            name='geographical_units',
            field=models.JSONField(blank=True, default=list, help_text='\n            Geographical units assigned with their CVD groups.\n            Structure: [\n                {\n                    "sql_id": "111",\n                    "name": "TIMANGA (CINKASSE)/KALYADA",\n                    "villages": ["1986"],\n                    "cvd_groups": [\n                        {\n                            "sql_id": "208",\n                            "name": "TIMANGA (CINKASSE)",\n                            "village_cvd": 1986,\n                            "villages": ["1986"]\n                        }\n                    ]\n                }\n            ]\n            '),
        ),
    ]
