# Generated by Django 4.0.4 on 2026-03-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_remove_facilitator_cvds_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitator',
            name='additional_administrative_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='stabilization_administrative_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
