# Generated by Django 4.0.4 on 2026-09-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_facilitator_additional_administrative_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitator',
            name='delete_by_user',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
