# Generated by Django 4.2.30 on 2026-09-17 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0019_basemodel_delete_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitator',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitator', to=settings.AUTH_USER_MODEL),
        ),
    ]
