# Generated by Django 4.0.4 on 2026-09-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_facilitator_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitator',
            name='additional_administrative_choices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='main_administrative_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='stabilization_administrative_choices',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
