# Generated by Django 4.0.4 on 2026-09-30 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0021_facilitator_localities_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocalities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrative_id', models.CharField(blank=True, max_length=255, null=True)),
                ('administrative_choices', models.JSONField(blank=True, null=True)),
                ('additional_administrative_choices', models.JSONField(blank=True, null=True)),
                ('village_ids', models.JSONField(blank=True, null=True)),
                ('additional_village_ids', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_localities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User localities',
                'verbose_name_plural': 'Users localities',
            },
        ),
        migrations.CreateModel(
            name='LocalityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('section', models.CharField(choices=[('assignment', 'Assignment villages'), ('stabilization', 'Stabilization villages'), ('additional', 'Additional villages'), ('intervention', 'Intervention localities'), ('intervention_additional', 'Additional intervention localities')], max_length=30)),
                ('main_before', models.CharField(blank=True, max_length=255, null=True)),
                ('main_after', models.CharField(blank=True, max_length=255, null=True)),
                ('choices_before', models.JSONField(blank=True, null=True)),
                ('choices_after', models.JSONField(blank=True, null=True)),
                ('villages_before', models.JSONField(blank=True, null=True)),
                ('villages_after', models.JSONField(blank=True, default=list)),
                ('added', models.JSONField(blank=True, default=list)),
                ('removed', models.JSONField(blank=True, default=list)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('localities_page', 'Localities page'), ('facilitator_form', 'Facilitator form'), ('facilitator_creation', 'Facilitator creation'), ('user_localities_page', 'User localities page'), ('grm', 'GRM'), ('mis_import', 'Imported from the MIS assignments'), ('initial_state', 'Initial state'), ('couchdb_rebuild', 'Rebuilt from CouchDB')], max_length=30)),
                ('changed_by_label', models.CharField(blank=True, max_length=200, null=True)),
                ('changed_at', models.DateTimeField(db_index=True)),
                ('approximate_date', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('facilitator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localities_history', to='authentication.facilitator')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localities_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Locality history',
                'verbose_name_plural': 'Localities history',
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='localityhistory',
            index=models.Index(fields=['facilitator', 'changed_at'], name='authenticat_facilit_4029c9_idx'),
        ),
        migrations.AddIndex(
            model_name='localityhistory',
            index=models.Index(fields=['user', 'changed_at'], name='authenticat_user_id_7960b5_idx'),
        ),
    ]
