PHASES_COLORS = [
    '#D9D9D9', # 0
    '#63D3AC', # 1
    '#F0788E', # 2
    '#F2CD86', # 3
    '#9095FF', # 4
    '#44967D', # 5
    '#BA79B7', # 6
    '#E9B9C2', # 7
]

PHASES_WITH_THEIR_NUMBERS = {
    "VISITES PREALABLES": 1,
    "MOBILISATION COMMUNAUTAIRE": 2,
    "PLANIFICATION": 3,
    "PRÉPARATION SOUS-PROJET": 4,
    "CONSULTATION  ET EXAMEN SOUS-PROJET": 5,
    "CONSULTATION ET EXAMEN SOUS-PROJET": 5,
    "MISE EN ŒUVRE DU SOUS-PROJET": 6,
    "CLOTURE ET REPLANIFICATION DU SOUS-PROJET": 7,
}